import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "./fonts";
import Providers from "./providers/providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en" 
      suppressHydrationWarning={true} 
      data-lt-installed={true}
      className={`${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers >
          {children}
        </Providers>
        </body>
    </html>
  );
}
